services:
  server:
    container_name: text-extract-container
    build:
      context: .
    ports:
      - 4400:8000
    develop:
      watch:
        - action: rebuild
          path: ./src
        - action: rebuild
          path: ./requirements.txt
